// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ai/apollon.proto

package edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai;

public final class ApollonProtos {
  private ApollonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DatabaseOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // optional string path = 2;
    boolean hasPath();
    String getPath();
    
    // optional bool persistStartegyMerge = 3 [default = true];
    boolean hasPersistStartegyMerge();
    boolean getPersistStartegyMerge();
    
    // optional bool saveOnClose = 4 [default = true];
    boolean hasSaveOnClose();
    boolean getSaveOnClose();
  }
  public static final class DatabaseOptions extends
      com.google.protobuf.GeneratedMessage
      implements DatabaseOptionsOrBuilder {
    // Use DatabaseOptions.newBuilder() to construct.
    private DatabaseOptions(Builder builder) {
      super(builder);
    }
    private DatabaseOptions(boolean noInit) {}
    
    private static final DatabaseOptions defaultInstance;
    public static DatabaseOptions getDefaultInstance() {
      return defaultInstance;
    }
    
    public DatabaseOptions getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_DatabaseOptions_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_DatabaseOptions_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string path = 2;
    public static final int PATH_FIELD_NUMBER = 2;
    private java.lang.Object path_;
    public boolean hasPath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          path_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool persistStartegyMerge = 3 [default = true];
    public static final int PERSISTSTARTEGYMERGE_FIELD_NUMBER = 3;
    private boolean persistStartegyMerge_;
    public boolean hasPersistStartegyMerge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getPersistStartegyMerge() {
      return persistStartegyMerge_;
    }
    
    // optional bool saveOnClose = 4 [default = true];
    public static final int SAVEONCLOSE_FIELD_NUMBER = 4;
    private boolean saveOnClose_;
    public boolean hasSaveOnClose() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getSaveOnClose() {
      return saveOnClose_;
    }
    
    private void initFields() {
      name_ = "";
      path_ = "";
      persistStartegyMerge_ = true;
      saveOnClose_ = true;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, persistStartegyMerge_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, saveOnClose_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, persistStartegyMerge_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, saveOnClose_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_DatabaseOptions_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_DatabaseOptions_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        persistStartegyMerge_ = true;
        bitField0_ = (bitField0_ & ~0x00000004);
        saveOnClose_ = true;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.path_ = path_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.persistStartegyMerge_ = persistStartegyMerge_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.saveOnClose_ = saveOnClose_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPath()) {
          setPath(other.getPath());
        }
        if (other.hasPersistStartegyMerge()) {
          setPersistStartegyMerge(other.getPersistStartegyMerge());
        }
        if (other.hasSaveOnClose()) {
          setSaveOnClose(other.getSaveOnClose());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              path_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              persistStartegyMerge_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              saveOnClose_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // optional string path = 2;
      private java.lang.Object path_ = "";
      public boolean hasPath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        path_ = value;
        onChanged();
        return this;
      }
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      void setPath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        path_ = value;
        onChanged();
      }
      
      // optional bool persistStartegyMerge = 3 [default = true];
      private boolean persistStartegyMerge_ = true;
      public boolean hasPersistStartegyMerge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getPersistStartegyMerge() {
        return persistStartegyMerge_;
      }
      public Builder setPersistStartegyMerge(boolean value) {
        bitField0_ |= 0x00000004;
        persistStartegyMerge_ = value;
        onChanged();
        return this;
      }
      public Builder clearPersistStartegyMerge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        persistStartegyMerge_ = true;
        onChanged();
        return this;
      }
      
      // optional bool saveOnClose = 4 [default = true];
      private boolean saveOnClose_ = true;
      public boolean hasSaveOnClose() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getSaveOnClose() {
        return saveOnClose_;
      }
      public Builder setSaveOnClose(boolean value) {
        bitField0_ |= 0x00000008;
        saveOnClose_ = value;
        onChanged();
        return this;
      }
      public Builder clearSaveOnClose() {
        bitField0_ = (bitField0_ & ~0x00000008);
        saveOnClose_ = true;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.DatabaseOptions)
    }
    
    static {
      defaultInstance = new DatabaseOptions(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.DatabaseOptions)
  }
  
  public interface MatchingOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required double acceptableMatch = 1;
    boolean hasAcceptableMatch();
    double getAcceptableMatch();
  }
  public static final class MatchingOptions extends
      com.google.protobuf.GeneratedMessage
      implements MatchingOptionsOrBuilder {
    // Use MatchingOptions.newBuilder() to construct.
    private MatchingOptions(Builder builder) {
      super(builder);
    }
    private MatchingOptions(boolean noInit) {}
    
    private static final MatchingOptions defaultInstance;
    public static MatchingOptions getDefaultInstance() {
      return defaultInstance;
    }
    
    public MatchingOptions getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_MatchingOptions_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_MatchingOptions_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required double acceptableMatch = 1;
    public static final int ACCEPTABLEMATCH_FIELD_NUMBER = 1;
    private double acceptableMatch_;
    public boolean hasAcceptableMatch() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public double getAcceptableMatch() {
      return acceptableMatch_;
    }
    
    private void initFields() {
      acceptableMatch_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAcceptableMatch()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, acceptableMatch_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, acceptableMatch_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_MatchingOptions_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_MatchingOptions_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        acceptableMatch_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.acceptableMatch_ = acceptableMatch_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions.getDefaultInstance()) return this;
        if (other.hasAcceptableMatch()) {
          setAcceptableMatch(other.getAcceptableMatch());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAcceptableMatch()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              acceptableMatch_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required double acceptableMatch = 1;
      private double acceptableMatch_ ;
      public boolean hasAcceptableMatch() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getAcceptableMatch() {
        return acceptableMatch_;
      }
      public Builder setAcceptableMatch(double value) {
        bitField0_ |= 0x00000001;
        acceptableMatch_ = value;
        onChanged();
        return this;
      }
      public Builder clearAcceptableMatch() {
        bitField0_ = (bitField0_ & ~0x00000001);
        acceptableMatch_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.MatchingOptions)
    }
    
    static {
      defaultInstance = new MatchingOptions(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.MatchingOptions)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_DatabaseOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_DatabaseOptions_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_MatchingOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_MatchingOptions_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ai/apollon.proto\022&edu.dhbw.mannheim.ti" +
      "gers.sumatra.proto\"l\n\017DatabaseOptions\022\014\n" +
      "\004name\030\001 \002(\t\022\014\n\004path\030\002 \001(\t\022\"\n\024persistStar" +
      "tegyMerge\030\003 \001(\010:\004true\022\031\n\013saveOnClose\030\004 \001" +
      "(\010:\004true\"*\n\017MatchingOptions\022\027\n\017acceptabl" +
      "eMatch\030\001 \002(\001BN\n=edu.dhbw.mannheim.tigers" +
      ".sumatra.proto.model.modules.impls.aiB\rA" +
      "pollonProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_DatabaseOptions_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_DatabaseOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_DatabaseOptions_descriptor,
              new java.lang.String[] { "Name", "Path", "PersistStartegyMerge", "SaveOnClose", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.DatabaseOptions.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_MatchingOptions_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_MatchingOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_MatchingOptions_descriptor,
              new java.lang.String[] { "AcceptableMatch", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.ApollonProtos.MatchingOptions.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
