// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ai/athena.proto

package edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai;

public final class AthenaProtos {
  private AthenaProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AvailablePlaysOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string plays = 1;
    java.util.List<String> getPlaysList();
    int getPlaysCount();
    String getPlays(int index);
  }
  public static final class AvailablePlays extends
      com.google.protobuf.GeneratedMessage
      implements AvailablePlaysOrBuilder {
    // Use AvailablePlays.newBuilder() to construct.
    private AvailablePlays(Builder builder) {
      super(builder);
    }
    private AvailablePlays(boolean noInit) {}
    
    private static final AvailablePlays defaultInstance;
    public static AvailablePlays getDefaultInstance() {
      return defaultInstance;
    }
    
    public AvailablePlays getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailablePlays_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailablePlays_fieldAccessorTable;
    }
    
    // repeated string plays = 1;
    public static final int PLAYS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList plays_;
    public java.util.List<String>
        getPlaysList() {
      return plays_;
    }
    public int getPlaysCount() {
      return plays_.size();
    }
    public String getPlays(int index) {
      return plays_.get(index);
    }
    
    private void initFields() {
      plays_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < plays_.size(); i++) {
        output.writeBytes(1, plays_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < plays_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(plays_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPlaysList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlaysOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailablePlays_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailablePlays_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        plays_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          plays_ = new com.google.protobuf.UnmodifiableLazyStringList(
              plays_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.plays_ = plays_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays.getDefaultInstance()) return this;
        if (!other.plays_.isEmpty()) {
          if (plays_.isEmpty()) {
            plays_ = other.plays_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePlaysIsMutable();
            plays_.addAll(other.plays_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensurePlaysIsMutable();
              plays_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string plays = 1;
      private com.google.protobuf.LazyStringList plays_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePlaysIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          plays_ = new com.google.protobuf.LazyStringArrayList(plays_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getPlaysList() {
        return java.util.Collections.unmodifiableList(plays_);
      }
      public int getPlaysCount() {
        return plays_.size();
      }
      public String getPlays(int index) {
        return plays_.get(index);
      }
      public Builder setPlays(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePlaysIsMutable();
        plays_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addPlays(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePlaysIsMutable();
        plays_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllPlays(
          java.lang.Iterable<String> values) {
        ensurePlaysIsMutable();
        super.addAll(values, plays_);
        onChanged();
        return this;
      }
      public Builder clearPlays() {
        plays_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addPlays(com.google.protobuf.ByteString value) {
        ensurePlaysIsMutable();
        plays_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.AvailablePlays)
    }
    
    static {
      defaultInstance = new AvailablePlays(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.AvailablePlays)
  }
  
  public interface PlayCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string playName = 1;
    boolean hasPlayName();
    String getPlayName();
    
    // optional int32 numRolesToAssign = 2;
    boolean hasNumRolesToAssign();
    int getNumRolesToAssign();
  }
  public static final class PlayCommand extends
      com.google.protobuf.GeneratedMessage
      implements PlayCommandOrBuilder {
    // Use PlayCommand.newBuilder() to construct.
    private PlayCommand(Builder builder) {
      super(builder);
    }
    private PlayCommand(boolean noInit) {}
    
    private static final PlayCommand defaultInstance;
    public static PlayCommand getDefaultInstance() {
      return defaultInstance;
    }
    
    public PlayCommand getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlayCommand_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlayCommand_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string playName = 1;
    public static final int PLAYNAME_FIELD_NUMBER = 1;
    private java.lang.Object playName_;
    public boolean hasPlayName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPlayName() {
      java.lang.Object ref = playName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          playName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPlayNameBytes() {
      java.lang.Object ref = playName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        playName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 numRolesToAssign = 2;
    public static final int NUMROLESTOASSIGN_FIELD_NUMBER = 2;
    private int numRolesToAssign_;
    public boolean hasNumRolesToAssign() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getNumRolesToAssign() {
      return numRolesToAssign_;
    }
    
    private void initFields() {
      playName_ = "";
      numRolesToAssign_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPlayNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, numRolesToAssign_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPlayNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numRolesToAssign_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlayCommand_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlayCommand_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        numRolesToAssign_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playName_ = playName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.numRolesToAssign_ = numRolesToAssign_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand.getDefaultInstance()) return this;
        if (other.hasPlayName()) {
          setPlayName(other.getPlayName());
        }
        if (other.hasNumRolesToAssign()) {
          setNumRolesToAssign(other.getNumRolesToAssign());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              playName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              numRolesToAssign_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string playName = 1;
      private java.lang.Object playName_ = "";
      public boolean hasPlayName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPlayName() {
        java.lang.Object ref = playName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          playName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPlayName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        playName_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playName_ = getDefaultInstance().getPlayName();
        onChanged();
        return this;
      }
      void setPlayName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        playName_ = value;
        onChanged();
      }
      
      // optional int32 numRolesToAssign = 2;
      private int numRolesToAssign_ ;
      public boolean hasNumRolesToAssign() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getNumRolesToAssign() {
        return numRolesToAssign_;
      }
      public Builder setNumRolesToAssign(int value) {
        bitField0_ |= 0x00000002;
        numRolesToAssign_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumRolesToAssign() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numRolesToAssign_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.PlayCommand)
    }
    
    static {
      defaultInstance = new PlayCommand(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.PlayCommand)
  }
  
  public interface PlaysToRemoveOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string playsToRemove = 1;
    java.util.List<String> getPlaysToRemoveList();
    int getPlaysToRemoveCount();
    String getPlaysToRemove(int index);
  }
  public static final class PlaysToRemove extends
      com.google.protobuf.GeneratedMessage
      implements PlaysToRemoveOrBuilder {
    // Use PlaysToRemove.newBuilder() to construct.
    private PlaysToRemove(Builder builder) {
      super(builder);
    }
    private PlaysToRemove(boolean noInit) {}
    
    private static final PlaysToRemove defaultInstance;
    public static PlaysToRemove getDefaultInstance() {
      return defaultInstance;
    }
    
    public PlaysToRemove getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlaysToRemove_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlaysToRemove_fieldAccessorTable;
    }
    
    // repeated string playsToRemove = 1;
    public static final int PLAYSTOREMOVE_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList playsToRemove_;
    public java.util.List<String>
        getPlaysToRemoveList() {
      return playsToRemove_;
    }
    public int getPlaysToRemoveCount() {
      return playsToRemove_.size();
    }
    public String getPlaysToRemove(int index) {
      return playsToRemove_.get(index);
    }
    
    private void initFields() {
      playsToRemove_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < playsToRemove_.size(); i++) {
        output.writeBytes(1, playsToRemove_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < playsToRemove_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(playsToRemove_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPlaysToRemoveList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlaysToRemove_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlaysToRemove_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playsToRemove_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          playsToRemove_ = new com.google.protobuf.UnmodifiableLazyStringList(
              playsToRemove_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.playsToRemove_ = playsToRemove_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove.getDefaultInstance()) return this;
        if (!other.playsToRemove_.isEmpty()) {
          if (playsToRemove_.isEmpty()) {
            playsToRemove_ = other.playsToRemove_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePlaysToRemoveIsMutable();
            playsToRemove_.addAll(other.playsToRemove_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensurePlaysToRemoveIsMutable();
              playsToRemove_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string playsToRemove = 1;
      private com.google.protobuf.LazyStringList playsToRemove_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePlaysToRemoveIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          playsToRemove_ = new com.google.protobuf.LazyStringArrayList(playsToRemove_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getPlaysToRemoveList() {
        return java.util.Collections.unmodifiableList(playsToRemove_);
      }
      public int getPlaysToRemoveCount() {
        return playsToRemove_.size();
      }
      public String getPlaysToRemove(int index) {
        return playsToRemove_.get(index);
      }
      public Builder setPlaysToRemove(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePlaysToRemoveIsMutable();
        playsToRemove_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addPlaysToRemove(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePlaysToRemoveIsMutable();
        playsToRemove_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllPlaysToRemove(
          java.lang.Iterable<String> values) {
        ensurePlaysToRemoveIsMutable();
        super.addAll(values, playsToRemove_);
        onChanged();
        return this;
      }
      public Builder clearPlaysToRemove() {
        playsToRemove_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addPlaysToRemove(com.google.protobuf.ByteString value) {
        ensurePlaysToRemoveIsMutable();
        playsToRemove_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.PlaysToRemove)
    }
    
    static {
      defaultInstance = new PlaysToRemove(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.PlaysToRemove)
  }
  
  public interface ForceNewDecisionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bool doAction = 1 [default = true];
    boolean hasDoAction();
    boolean getDoAction();
  }
  public static final class ForceNewDecision extends
      com.google.protobuf.GeneratedMessage
      implements ForceNewDecisionOrBuilder {
    // Use ForceNewDecision.newBuilder() to construct.
    private ForceNewDecision(Builder builder) {
      super(builder);
    }
    private ForceNewDecision(boolean noInit) {}
    
    private static final ForceNewDecision defaultInstance;
    public static ForceNewDecision getDefaultInstance() {
      return defaultInstance;
    }
    
    public ForceNewDecision getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ForceNewDecision_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ForceNewDecision_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bool doAction = 1 [default = true];
    public static final int DOACTION_FIELD_NUMBER = 1;
    private boolean doAction_;
    public boolean hasDoAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getDoAction() {
      return doAction_;
    }
    
    private void initFields() {
      doAction_ = true;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, doAction_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, doAction_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecisionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ForceNewDecision_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ForceNewDecision_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        doAction_ = true;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.doAction_ = doAction_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision.getDefaultInstance()) return this;
        if (other.hasDoAction()) {
          setDoAction(other.getDoAction());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              doAction_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bool doAction = 1 [default = true];
      private boolean doAction_ = true;
      public boolean hasDoAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getDoAction() {
        return doAction_;
      }
      public Builder setDoAction(boolean value) {
        bitField0_ |= 0x00000001;
        doAction_ = value;
        onChanged();
        return this;
      }
      public Builder clearDoAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        doAction_ = true;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.ForceNewDecision)
    }
    
    static {
      defaultInstance = new ForceNewDecision(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.ForceNewDecision)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailablePlays_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailablePlays_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlayCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlayCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlaysToRemove_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlaysToRemove_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ForceNewDecision_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ForceNewDecision_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ai/athena.proto\022&edu.dhbw.mannheim.tig" +
      "ers.sumatra.proto\"\037\n\016AvailablePlays\022\r\n\005p" +
      "lays\030\001 \003(\t\"9\n\013PlayCommand\022\020\n\010playName\030\001 " +
      "\002(\t\022\030\n\020numRolesToAssign\030\002 \001(\005\"&\n\rPlaysTo" +
      "Remove\022\025\n\rplaysToRemove\030\001 \003(\t\"*\n\020ForceNe" +
      "wDecision\022\026\n\010doAction\030\001 \001(\010:\004trueBM\n=edu" +
      ".dhbw.mannheim.tigers.sumatra.proto.mode" +
      "l.modules.impls.aiB\014AthenaProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailablePlays_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailablePlays_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailablePlays_descriptor,
              new java.lang.String[] { "Plays", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.AvailablePlays.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlayCommand_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlayCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlayCommand_descriptor,
              new java.lang.String[] { "PlayName", "NumRolesToAssign", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlayCommand.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlaysToRemove_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlaysToRemove_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_PlaysToRemove_descriptor,
              new java.lang.String[] { "PlaysToRemove", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.PlaysToRemove.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ForceNewDecision_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ForceNewDecision_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ForceNewDecision_descriptor,
              new java.lang.String[] { "DoAction", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.AthenaProtos.ForceNewDecision.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
