// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ai/lachesis.proto

package edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai;

public final class LachesisProtos {
  private LachesisProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AvailableRolesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string roles = 1;
    java.util.List<String> getRolesList();
    int getRolesCount();
    String getRoles(int index);
  }
  public static final class AvailableRoles extends
      com.google.protobuf.GeneratedMessage
      implements AvailableRolesOrBuilder {
    // Use AvailableRoles.newBuilder() to construct.
    private AvailableRoles(Builder builder) {
      super(builder);
    }
    private AvailableRoles(boolean noInit) {}
    
    private static final AvailableRoles defaultInstance;
    public static AvailableRoles getDefaultInstance() {
      return defaultInstance;
    }
    
    public AvailableRoles getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailableRoles_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailableRoles_fieldAccessorTable;
    }
    
    // repeated string roles = 1;
    public static final int ROLES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList roles_;
    public java.util.List<String>
        getRolesList() {
      return roles_;
    }
    public int getRolesCount() {
      return roles_.size();
    }
    public String getRoles(int index) {
      return roles_.get(index);
    }
    
    private void initFields() {
      roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < roles_.size(); i++) {
        output.writeBytes(1, roles_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < roles_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(roles_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getRolesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRolesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailableRoles_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailableRoles_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          roles_ = new com.google.protobuf.UnmodifiableLazyStringList(
              roles_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.roles_ = roles_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles.getDefaultInstance()) return this;
        if (!other.roles_.isEmpty()) {
          if (roles_.isEmpty()) {
            roles_ = other.roles_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRolesIsMutable();
            roles_.addAll(other.roles_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureRolesIsMutable();
              roles_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string roles = 1;
      private com.google.protobuf.LazyStringList roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRolesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          roles_ = new com.google.protobuf.LazyStringArrayList(roles_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getRolesList() {
        return java.util.Collections.unmodifiableList(roles_);
      }
      public int getRolesCount() {
        return roles_.size();
      }
      public String getRoles(int index) {
        return roles_.get(index);
      }
      public Builder setRoles(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
        roles_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addRoles(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
        roles_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllRoles(
          java.lang.Iterable<String> values) {
        ensureRolesIsMutable();
        super.addAll(values, roles_);
        onChanged();
        return this;
      }
      public Builder clearRoles() {
        roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addRoles(com.google.protobuf.ByteString value) {
        ensureRolesIsMutable();
        roles_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.AvailableRoles)
    }
    
    static {
      defaultInstance = new AvailableRoles(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.AvailableRoles)
  }
  
  public interface RoleCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string roleName = 1;
    boolean hasRoleName();
    String getRoleName();
    
    // optional int32 botId = 2;
    boolean hasBotId();
    int getBotId();
  }
  public static final class RoleCommand extends
      com.google.protobuf.GeneratedMessage
      implements RoleCommandOrBuilder {
    // Use RoleCommand.newBuilder() to construct.
    private RoleCommand(Builder builder) {
      super(builder);
    }
    private RoleCommand(boolean noInit) {}
    
    private static final RoleCommand defaultInstance;
    public static RoleCommand getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleCommand getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_RoleCommand_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_RoleCommand_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string roleName = 1;
    public static final int ROLENAME_FIELD_NUMBER = 1;
    private java.lang.Object roleName_;
    public boolean hasRoleName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRoleName() {
      java.lang.Object ref = roleName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          roleName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRoleNameBytes() {
      java.lang.Object ref = roleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        roleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 botId = 2;
    public static final int BOTID_FIELD_NUMBER = 2;
    private int botId_;
    public boolean hasBotId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getBotId() {
      return botId_;
    }
    
    private void initFields() {
      roleName_ = "";
      botId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRoleName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRoleNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, botId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRoleNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, botId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_RoleCommand_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_RoleCommand_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        roleName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        botId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roleName_ = roleName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.botId_ = botId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand.getDefaultInstance()) return this;
        if (other.hasRoleName()) {
          setRoleName(other.getRoleName());
        }
        if (other.hasBotId()) {
          setBotId(other.getBotId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRoleName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              roleName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              botId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string roleName = 1;
      private java.lang.Object roleName_ = "";
      public boolean hasRoleName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRoleName() {
        java.lang.Object ref = roleName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          roleName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRoleName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        roleName_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoleName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roleName_ = getDefaultInstance().getRoleName();
        onChanged();
        return this;
      }
      void setRoleName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        roleName_ = value;
        onChanged();
      }
      
      // optional int32 botId = 2;
      private int botId_ ;
      public boolean hasBotId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getBotId() {
        return botId_;
      }
      public Builder setBotId(int value) {
        bitField0_ |= 0x00000002;
        botId_ = value;
        onChanged();
        return this;
      }
      public Builder clearBotId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        botId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.RoleCommand)
    }
    
    static {
      defaultInstance = new RoleCommand(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.RoleCommand)
  }
  
  public interface ClearRoleCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bool doAction = 1 [default = true];
    boolean hasDoAction();
    boolean getDoAction();
  }
  public static final class ClearRoleCommand extends
      com.google.protobuf.GeneratedMessage
      implements ClearRoleCommandOrBuilder {
    // Use ClearRoleCommand.newBuilder() to construct.
    private ClearRoleCommand(Builder builder) {
      super(builder);
    }
    private ClearRoleCommand(boolean noInit) {}
    
    private static final ClearRoleCommand defaultInstance;
    public static ClearRoleCommand getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClearRoleCommand getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ClearRoleCommand_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ClearRoleCommand_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bool doAction = 1 [default = true];
    public static final int DOACTION_FIELD_NUMBER = 1;
    private boolean doAction_;
    public boolean hasDoAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getDoAction() {
      return doAction_;
    }
    
    private void initFields() {
      doAction_ = true;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, doAction_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, doAction_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ClearRoleCommand_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ClearRoleCommand_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        doAction_ = true;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.doAction_ = doAction_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand.getDefaultInstance()) return this;
        if (other.hasDoAction()) {
          setDoAction(other.getDoAction());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              doAction_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bool doAction = 1 [default = true];
      private boolean doAction_ = true;
      public boolean hasDoAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getDoAction() {
        return doAction_;
      }
      public Builder setDoAction(boolean value) {
        bitField0_ |= 0x00000001;
        doAction_ = value;
        onChanged();
        return this;
      }
      public Builder clearDoAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        doAction_ = true;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.ClearRoleCommand)
    }
    
    static {
      defaultInstance = new ClearRoleCommand(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.ClearRoleCommand)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailableRoles_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailableRoles_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_RoleCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_RoleCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ClearRoleCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ClearRoleCommand_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ai/lachesis.proto\022&edu.dhbw.mannheim.t" +
      "igers.sumatra.proto\"\037\n\016AvailableRoles\022\r\n" +
      "\005roles\030\001 \003(\t\".\n\013RoleCommand\022\020\n\010roleName\030" +
      "\001 \002(\t\022\r\n\005botId\030\002 \001(\005\"*\n\020ClearRoleCommand" +
      "\022\026\n\010doAction\030\001 \001(\010:\004trueBO\n=edu.dhbw.man" +
      "nheim.tigers.sumatra.proto.model.modules" +
      ".impls.aiB\016LachesisProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailableRoles_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailableRoles_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_AvailableRoles_descriptor,
              new java.lang.String[] { "Roles", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.AvailableRoles.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_RoleCommand_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_RoleCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_RoleCommand_descriptor,
              new java.lang.String[] { "RoleName", "BotId", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.RoleCommand.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ClearRoleCommand_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ClearRoleCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ClearRoleCommand_descriptor,
              new java.lang.String[] { "DoAction", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.ai.LachesisProtos.ClearRoleCommand.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
