// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mainpresenter.proto

package edu.dhbw.mannheim.tigers.sumatra.proto.presenter;

public final class MainPresenterProtos {
  private MainPresenterProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ModuliConfigFileOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string file = 1;
    boolean hasFile();
    String getFile();
  }
  public static final class ModuliConfigFile extends
      com.google.protobuf.GeneratedMessage
      implements ModuliConfigFileOrBuilder {
    // Use ModuliConfigFile.newBuilder() to construct.
    private ModuliConfigFile(Builder builder) {
      super(builder);
    }
    private ModuliConfigFile(boolean noInit) {}
    
    private static final ModuliConfigFile defaultInstance;
    public static ModuliConfigFile getDefaultInstance() {
      return defaultInstance;
    }
    
    public ModuliConfigFile getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModuliConfigFile_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModuliConfigFile_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string file = 1;
    public static final int FILE_FIELD_NUMBER = 1;
    private java.lang.Object file_;
    public boolean hasFile() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFile() {
      java.lang.Object ref = file_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          file_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFileBytes() {
      java.lang.Object ref = file_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        file_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      file_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFile()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFileBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFileBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModuliConfigFile_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModuliConfigFile_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        file_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile result = new edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.file_ = file_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile.getDefaultInstance()) return this;
        if (other.hasFile()) {
          setFile(other.getFile());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFile()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              file_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string file = 1;
      private java.lang.Object file_ = "";
      public boolean hasFile() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFile() {
        java.lang.Object ref = file_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          file_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFile(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        file_ = value;
        onChanged();
        return this;
      }
      public Builder clearFile() {
        bitField0_ = (bitField0_ & ~0x00000001);
        file_ = getDefaultInstance().getFile();
        onChanged();
        return this;
      }
      void setFile(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        file_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.ModuliConfigFile)
    }
    
    static {
      defaultInstance = new ModuliConfigFile(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.ModuliConfigFile)
  }
  
  public interface FilenameArrayOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string item = 1;
    java.util.List<String> getItemList();
    int getItemCount();
    String getItem(int index);
  }
  public static final class FilenameArray extends
      com.google.protobuf.GeneratedMessage
      implements FilenameArrayOrBuilder {
    // Use FilenameArray.newBuilder() to construct.
    private FilenameArray(Builder builder) {
      super(builder);
    }
    private FilenameArray(boolean noInit) {}
    
    private static final FilenameArray defaultInstance;
    public static FilenameArray getDefaultInstance() {
      return defaultInstance;
    }
    
    public FilenameArray getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_FilenameArray_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_FilenameArray_fieldAccessorTable;
    }
    
    // repeated string item = 1;
    public static final int ITEM_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList item_;
    public java.util.List<String>
        getItemList() {
      return item_;
    }
    public int getItemCount() {
      return item_.size();
    }
    public String getItem(int index) {
      return item_.get(index);
    }
    
    private void initFields() {
      item_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < item_.size(); i++) {
        output.writeBytes(1, item_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < item_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(item_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getItemList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_FilenameArray_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_FilenameArray_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        item_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray result = new edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          item_ = new com.google.protobuf.UnmodifiableLazyStringList(
              item_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.item_ = item_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray.getDefaultInstance()) return this;
        if (!other.item_.isEmpty()) {
          if (item_.isEmpty()) {
            item_ = other.item_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemIsMutable();
            item_.addAll(other.item_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureItemIsMutable();
              item_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string item = 1;
      private com.google.protobuf.LazyStringList item_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          item_ = new com.google.protobuf.LazyStringArrayList(item_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getItemList() {
        return java.util.Collections.unmodifiableList(item_);
      }
      public int getItemCount() {
        return item_.size();
      }
      public String getItem(int index) {
        return item_.get(index);
      }
      public Builder setItem(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureItemIsMutable();
        item_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addItem(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureItemIsMutable();
        item_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllItem(
          java.lang.Iterable<String> values) {
        ensureItemIsMutable();
        super.addAll(values, item_);
        onChanged();
        return this;
      }
      public Builder clearItem() {
        item_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addItem(com.google.protobuf.ByteString value) {
        ensureItemIsMutable();
        item_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.FilenameArray)
    }
    
    static {
      defaultInstance = new FilenameArray(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.FilenameArray)
  }
  
  public interface EmergencyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bool mode = 1;
    boolean hasMode();
    boolean getMode();
  }
  public static final class Emergency extends
      com.google.protobuf.GeneratedMessage
      implements EmergencyOrBuilder {
    // Use Emergency.newBuilder() to construct.
    private Emergency(Builder builder) {
      super(builder);
    }
    private Emergency(boolean noInit) {}
    
    private static final Emergency defaultInstance;
    public static Emergency getDefaultInstance() {
      return defaultInstance;
    }
    
    public Emergency getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Emergency_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Emergency_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bool mode = 1;
    public static final int MODE_FIELD_NUMBER = 1;
    private boolean mode_;
    public boolean hasMode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getMode() {
      return mode_;
    }
    
    private void initFields() {
      mode_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, mode_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, mode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.EmergencyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Emergency_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Emergency_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        mode_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency result = new edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mode_ = mode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency.getDefaultInstance()) return this;
        if (other.hasMode()) {
          setMode(other.getMode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mode_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool mode = 1;
      private boolean mode_ ;
      public boolean hasMode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getMode() {
        return mode_;
      }
      public Builder setMode(boolean value) {
        bitField0_ |= 0x00000001;
        mode_ = value;
        onChanged();
        return this;
      }
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mode_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.Emergency)
    }
    
    static {
      defaultInstance = new Emergency(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.Emergency)
  }
  
  public interface ModulesStateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string state = 1;
    boolean hasState();
    String getState();
  }
  public static final class ModulesState extends
      com.google.protobuf.GeneratedMessage
      implements ModulesStateOrBuilder {
    // Use ModulesState.newBuilder() to construct.
    private ModulesState(Builder builder) {
      super(builder);
    }
    private ModulesState(boolean noInit) {}
    
    private static final ModulesState defaultInstance;
    public static ModulesState getDefaultInstance() {
      return defaultInstance;
    }
    
    public ModulesState getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModulesState_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModulesState_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string state = 1;
    public static final int STATE_FIELD_NUMBER = 1;
    private java.lang.Object state_;
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          state_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      state_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStateBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStateBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModulesState_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModulesState_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState result = new edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasState()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              state_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string state = 1;
      private java.lang.Object state_ = "";
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setState(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      void setState(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.ModulesState)
    }
    
    static {
      defaultInstance = new ModulesState(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.ModulesState)
  }
  
  public interface FpsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required float fps = 1;
    boolean hasFps();
    float getFps();
  }
  public static final class Fps extends
      com.google.protobuf.GeneratedMessage
      implements FpsOrBuilder {
    // Use Fps.newBuilder() to construct.
    private Fps(Builder builder) {
      super(builder);
    }
    private Fps(boolean noInit) {}
    
    private static final Fps defaultInstance;
    public static Fps getDefaultInstance() {
      return defaultInstance;
    }
    
    public Fps getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Fps_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Fps_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required float fps = 1;
    public static final int FPS_FIELD_NUMBER = 1;
    private float fps_;
    public boolean hasFps() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public float getFps() {
      return fps_;
    }
    
    private void initFields() {
      fps_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFps()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, fps_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, fps_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FpsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Fps_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Fps_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        fps_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps result = new edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fps_ = fps_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps.getDefaultInstance()) return this;
        if (other.hasFps()) {
          setFps(other.getFps());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFps()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              fps_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required float fps = 1;
      private float fps_ ;
      public boolean hasFps() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public float getFps() {
        return fps_;
      }
      public Builder setFps(float value) {
        bitField0_ |= 0x00000001;
        fps_ = value;
        onChanged();
        return this;
      }
      public Builder clearFps() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fps_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.Fps)
    }
    
    static {
      defaultInstance = new Fps(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.Fps)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModuliConfigFile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModuliConfigFile_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_FilenameArray_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_FilenameArray_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Emergency_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Emergency_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModulesState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModulesState_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Fps_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Fps_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023mainpresenter.proto\022&edu.dhbw.mannheim" +
      ".tigers.sumatra.proto\" \n\020ModuliConfigFil" +
      "e\022\014\n\004file\030\001 \002(\t\"\035\n\rFilenameArray\022\014\n\004item" +
      "\030\001 \003(\t\"\031\n\tEmergency\022\014\n\004mode\030\001 \002(\010\"\035\n\014Mod" +
      "ulesState\022\r\n\005state\030\001 \002(\t\"\022\n\003Fps\022\013\n\003fps\030\001" +
      " \002(\002BG\n0edu.dhbw.mannheim.tigers.sumatra" +
      ".proto.presenterB\023MainPresenterProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModuliConfigFile_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModuliConfigFile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModuliConfigFile_descriptor,
              new java.lang.String[] { "File", },
              edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModuliConfigFile.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_FilenameArray_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_FilenameArray_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_FilenameArray_descriptor,
              new java.lang.String[] { "Item", },
              edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.FilenameArray.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Emergency_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Emergency_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Emergency_descriptor,
              new java.lang.String[] { "Mode", },
              edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Emergency.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModulesState_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModulesState_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_ModulesState_descriptor,
              new java.lang.String[] { "State", },
              edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.ModulesState.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Fps_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Fps_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Fps_descriptor,
              new java.lang.String[] { "Fps", },
              edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.presenter.MainPresenterProtos.Fps.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
