// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: botConnection.proto

package edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm;

public final class BotConnProtos {
  private BotConnProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BotStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 botId = 1;
    boolean hasBotId();
    int getBotId();
    
    // optional bool connected = 2 [default = false];
    boolean hasConnected();
    boolean getConnected();
    
    // optional bool available = 3 [default = true];
    boolean hasAvailable();
    boolean getAvailable();
    
    // optional bool blocked = 4 [default = false];
    boolean hasBlocked();
    boolean getBlocked();
  }
  public static final class BotStatus extends
      com.google.protobuf.GeneratedMessage
      implements BotStatusOrBuilder {
    // Use BotStatus.newBuilder() to construct.
    private BotStatus(Builder builder) {
      super(builder);
    }
    private BotStatus(boolean noInit) {}
    
    private static final BotStatus defaultInstance;
    public static BotStatus getDefaultInstance() {
      return defaultInstance;
    }
    
    public BotStatus getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotStatus_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotStatus_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 botId = 1;
    public static final int BOTID_FIELD_NUMBER = 1;
    private int botId_;
    public boolean hasBotId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getBotId() {
      return botId_;
    }
    
    // optional bool connected = 2 [default = false];
    public static final int CONNECTED_FIELD_NUMBER = 2;
    private boolean connected_;
    public boolean hasConnected() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getConnected() {
      return connected_;
    }
    
    // optional bool available = 3 [default = true];
    public static final int AVAILABLE_FIELD_NUMBER = 3;
    private boolean available_;
    public boolean hasAvailable() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getAvailable() {
      return available_;
    }
    
    // optional bool blocked = 4 [default = false];
    public static final int BLOCKED_FIELD_NUMBER = 4;
    private boolean blocked_;
    public boolean hasBlocked() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getBlocked() {
      return blocked_;
    }
    
    private void initFields() {
      botId_ = 0;
      connected_ = false;
      available_ = true;
      blocked_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasBotId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, botId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, connected_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, available_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, blocked_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, botId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, connected_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, available_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, blocked_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotStatus_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotStatus_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        botId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        connected_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        available_ = true;
        bitField0_ = (bitField0_ & ~0x00000004);
        blocked_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.botId_ = botId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.connected_ = connected_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.available_ = available_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.blocked_ = blocked_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.getDefaultInstance()) return this;
        if (other.hasBotId()) {
          setBotId(other.getBotId());
        }
        if (other.hasConnected()) {
          setConnected(other.getConnected());
        }
        if (other.hasAvailable()) {
          setAvailable(other.getAvailable());
        }
        if (other.hasBlocked()) {
          setBlocked(other.getBlocked());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasBotId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              botId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              connected_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              available_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              blocked_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 botId = 1;
      private int botId_ ;
      public boolean hasBotId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getBotId() {
        return botId_;
      }
      public Builder setBotId(int value) {
        bitField0_ |= 0x00000001;
        botId_ = value;
        onChanged();
        return this;
      }
      public Builder clearBotId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        botId_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool connected = 2 [default = false];
      private boolean connected_ ;
      public boolean hasConnected() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getConnected() {
        return connected_;
      }
      public Builder setConnected(boolean value) {
        bitField0_ |= 0x00000002;
        connected_ = value;
        onChanged();
        return this;
      }
      public Builder clearConnected() {
        bitField0_ = (bitField0_ & ~0x00000002);
        connected_ = false;
        onChanged();
        return this;
      }
      
      // optional bool available = 3 [default = true];
      private boolean available_ = true;
      public boolean hasAvailable() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getAvailable() {
        return available_;
      }
      public Builder setAvailable(boolean value) {
        bitField0_ |= 0x00000004;
        available_ = value;
        onChanged();
        return this;
      }
      public Builder clearAvailable() {
        bitField0_ = (bitField0_ & ~0x00000004);
        available_ = true;
        onChanged();
        return this;
      }
      
      // optional bool blocked = 4 [default = false];
      private boolean blocked_ ;
      public boolean hasBlocked() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getBlocked() {
        return blocked_;
      }
      public Builder setBlocked(boolean value) {
        bitField0_ |= 0x00000008;
        blocked_ = value;
        onChanged();
        return this;
      }
      public Builder clearBlocked() {
        bitField0_ = (bitField0_ & ~0x00000008);
        blocked_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.BotStatus)
    }
    
    static {
      defaultInstance = new BotStatus(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.BotStatus)
  }
  
  public interface BotConnOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .edu.dhbw.mannheim.tigers.sumatra.proto.BotStatus botStatus = 1;
    java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus> 
        getBotStatusList();
    edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus getBotStatus(int index);
    int getBotStatusCount();
    java.util.List<? extends edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatusOrBuilder> 
        getBotStatusOrBuilderList();
    edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatusOrBuilder getBotStatusOrBuilder(
        int index);
  }
  public static final class BotConn extends
      com.google.protobuf.GeneratedMessage
      implements BotConnOrBuilder {
    // Use BotConn.newBuilder() to construct.
    private BotConn(Builder builder) {
      super(builder);
    }
    private BotConn(boolean noInit) {}
    
    private static final BotConn defaultInstance;
    public static BotConn getDefaultInstance() {
      return defaultInstance;
    }
    
    public BotConn getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotConn_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotConn_fieldAccessorTable;
    }
    
    // repeated .edu.dhbw.mannheim.tigers.sumatra.proto.BotStatus botStatus = 1;
    public static final int BOTSTATUS_FIELD_NUMBER = 1;
    private java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus> botStatus_;
    public java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus> getBotStatusList() {
      return botStatus_;
    }
    public java.util.List<? extends edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatusOrBuilder> 
        getBotStatusOrBuilderList() {
      return botStatus_;
    }
    public int getBotStatusCount() {
      return botStatus_.size();
    }
    public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus getBotStatus(int index) {
      return botStatus_.get(index);
    }
    public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatusOrBuilder getBotStatusOrBuilder(
        int index) {
      return botStatus_.get(index);
    }
    
    private void initFields() {
      botStatus_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getBotStatusCount(); i++) {
        if (!getBotStatus(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < botStatus_.size(); i++) {
        output.writeMessage(1, botStatus_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < botStatus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, botStatus_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotConn_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotConn_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBotStatusFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (botStatusBuilder_ == null) {
          botStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          botStatusBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn(this);
        int from_bitField0_ = bitField0_;
        if (botStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            botStatus_ = java.util.Collections.unmodifiableList(botStatus_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.botStatus_ = botStatus_;
        } else {
          result.botStatus_ = botStatusBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn.getDefaultInstance()) return this;
        if (botStatusBuilder_ == null) {
          if (!other.botStatus_.isEmpty()) {
            if (botStatus_.isEmpty()) {
              botStatus_ = other.botStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBotStatusIsMutable();
              botStatus_.addAll(other.botStatus_);
            }
            onChanged();
          }
        } else {
          if (!other.botStatus_.isEmpty()) {
            if (botStatusBuilder_.isEmpty()) {
              botStatusBuilder_.dispose();
              botStatusBuilder_ = null;
              botStatus_ = other.botStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
              botStatusBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBotStatusFieldBuilder() : null;
            } else {
              botStatusBuilder_.addAllMessages(other.botStatus_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getBotStatusCount(); i++) {
          if (!getBotStatus(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder subBuilder = edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBotStatus(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .edu.dhbw.mannheim.tigers.sumatra.proto.BotStatus botStatus = 1;
      private java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus> botStatus_ =
        java.util.Collections.emptyList();
      private void ensureBotStatusIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          botStatus_ = new java.util.ArrayList<edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus>(botStatus_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatusOrBuilder> botStatusBuilder_;
      
      public java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus> getBotStatusList() {
        if (botStatusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(botStatus_);
        } else {
          return botStatusBuilder_.getMessageList();
        }
      }
      public int getBotStatusCount() {
        if (botStatusBuilder_ == null) {
          return botStatus_.size();
        } else {
          return botStatusBuilder_.getCount();
        }
      }
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus getBotStatus(int index) {
        if (botStatusBuilder_ == null) {
          return botStatus_.get(index);
        } else {
          return botStatusBuilder_.getMessage(index);
        }
      }
      public Builder setBotStatus(
          int index, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus value) {
        if (botStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBotStatusIsMutable();
          botStatus_.set(index, value);
          onChanged();
        } else {
          botStatusBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBotStatus(
          int index, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder builderForValue) {
        if (botStatusBuilder_ == null) {
          ensureBotStatusIsMutable();
          botStatus_.set(index, builderForValue.build());
          onChanged();
        } else {
          botStatusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBotStatus(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus value) {
        if (botStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBotStatusIsMutable();
          botStatus_.add(value);
          onChanged();
        } else {
          botStatusBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBotStatus(
          int index, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus value) {
        if (botStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBotStatusIsMutable();
          botStatus_.add(index, value);
          onChanged();
        } else {
          botStatusBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBotStatus(
          edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder builderForValue) {
        if (botStatusBuilder_ == null) {
          ensureBotStatusIsMutable();
          botStatus_.add(builderForValue.build());
          onChanged();
        } else {
          botStatusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBotStatus(
          int index, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder builderForValue) {
        if (botStatusBuilder_ == null) {
          ensureBotStatusIsMutable();
          botStatus_.add(index, builderForValue.build());
          onChanged();
        } else {
          botStatusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBotStatus(
          java.lang.Iterable<? extends edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus> values) {
        if (botStatusBuilder_ == null) {
          ensureBotStatusIsMutable();
          super.addAll(values, botStatus_);
          onChanged();
        } else {
          botStatusBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBotStatus() {
        if (botStatusBuilder_ == null) {
          botStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          botStatusBuilder_.clear();
        }
        return this;
      }
      public Builder removeBotStatus(int index) {
        if (botStatusBuilder_ == null) {
          ensureBotStatusIsMutable();
          botStatus_.remove(index);
          onChanged();
        } else {
          botStatusBuilder_.remove(index);
        }
        return this;
      }
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder getBotStatusBuilder(
          int index) {
        return getBotStatusFieldBuilder().getBuilder(index);
      }
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatusOrBuilder getBotStatusOrBuilder(
          int index) {
        if (botStatusBuilder_ == null) {
          return botStatus_.get(index);  } else {
          return botStatusBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatusOrBuilder> 
           getBotStatusOrBuilderList() {
        if (botStatusBuilder_ != null) {
          return botStatusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(botStatus_);
        }
      }
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder addBotStatusBuilder() {
        return getBotStatusFieldBuilder().addBuilder(
            edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.getDefaultInstance());
      }
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder addBotStatusBuilder(
          int index) {
        return getBotStatusFieldBuilder().addBuilder(
            index, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.getDefaultInstance());
      }
      public java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder> 
           getBotStatusBuilderList() {
        return getBotStatusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatusOrBuilder> 
          getBotStatusFieldBuilder() {
        if (botStatusBuilder_ == null) {
          botStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder, edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatusOrBuilder>(
                  botStatus_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          botStatus_ = null;
        }
        return botStatusBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.BotConn)
    }
    
    static {
      defaultInstance = new BotConn(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.BotConn)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotStatus_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotConn_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotConn_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023botConnection.proto\022&edu.dhbw.mannheim" +
      ".tigers.sumatra.proto\"e\n\tBotStatus\022\r\n\005bo" +
      "tId\030\001 \002(\005\022\030\n\tconnected\030\002 \001(\010:\005false\022\027\n\ta" +
      "vailable\030\003 \001(\010:\004true\022\026\n\007blocked\030\004 \001(\010:\005f" +
      "alse\"O\n\007BotConn\022D\n\tbotStatus\030\001 \003(\01321.edu" +
      ".dhbw.mannheim.tigers.sumatra.proto.BotS" +
      "tatusBO\n>edu.dhbw.mannheim.tigers.sumatr" +
      "a.proto.model.modules.impls.rcmB\rBotConn" +
      "Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotStatus_descriptor,
              new java.lang.String[] { "BotId", "Connected", "Available", "Blocked", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotStatus.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotConn_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotConn_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotConn_descriptor,
              new java.lang.String[] { "BotStatus", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.BotConnProtos.BotConn.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
