// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifeSign.proto

package edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm;

public final class LifeSignProtos {
  private LifeSignProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LifeSignOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // optional int32 activeBot = 2;
    boolean hasActiveBot();
    int getActiveBot();
  }
  public static final class LifeSign extends
      com.google.protobuf.GeneratedMessage
      implements LifeSignOrBuilder {
    // Use LifeSign.newBuilder() to construct.
    private LifeSign(Builder builder) {
      super(builder);
    }
    private LifeSign(boolean noInit) {}
    
    private static final LifeSign defaultInstance;
    public static LifeSign getDefaultInstance() {
      return defaultInstance;
    }
    
    public LifeSign getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_LifeSign_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_LifeSign_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 activeBot = 2;
    public static final int ACTIVEBOT_FIELD_NUMBER = 2;
    private int activeBot_;
    public boolean hasActiveBot() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getActiveBot() {
      return activeBot_;
    }
    
    private void initFields() {
      name_ = "";
      activeBot_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, activeBot_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, activeBot_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSignOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_LifeSign_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_LifeSign_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        activeBot_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.activeBot_ = activeBot_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasActiveBot()) {
          setActiveBot(other.getActiveBot());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              activeBot_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // optional int32 activeBot = 2;
      private int activeBot_ ;
      public boolean hasActiveBot() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getActiveBot() {
        return activeBot_;
      }
      public Builder setActiveBot(int value) {
        bitField0_ |= 0x00000002;
        activeBot_ = value;
        onChanged();
        return this;
      }
      public Builder clearActiveBot() {
        bitField0_ = (bitField0_ & ~0x00000002);
        activeBot_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.LifeSign)
    }
    
    static {
      defaultInstance = new LifeSign(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.LifeSign)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_LifeSign_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_LifeSign_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016lifeSign.proto\022&edu.dhbw.mannheim.tige" +
      "rs.sumatra.proto\"+\n\010LifeSign\022\014\n\004name\030\001 \002" +
      "(\t\022\021\n\tactiveBot\030\002 \001(\005BP\n>edu.dhbw.mannhe" +
      "im.tigers.sumatra.proto.model.modules.im" +
      "pls.rcmB\016LifeSignProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_LifeSign_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_LifeSign_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_LifeSign_descriptor,
              new java.lang.String[] { "Name", "ActiveBot", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.modules.impls.rcm.LifeSignProtos.LifeSign.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
