// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bot.proto

package edu.dhbw.mannheim.tigers.sumatra.proto.model;

public final class BotProtos {
  private BotProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BotOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string ip = 1;
    boolean hasIp();
    String getIp();
    
    // required int32 port = 2;
    boolean hasPort();
    int getPort();
    
    // required string name = 3;
    boolean hasName();
    String getName();
  }
  public static final class Bot extends
      com.google.protobuf.GeneratedMessage
      implements BotOrBuilder {
    // Use Bot.newBuilder() to construct.
    private Bot(Builder builder) {
      super(builder);
    }
    private Bot(boolean noInit) {}
    
    private static final Bot defaultInstance;
    public static Bot getDefaultInstance() {
      return defaultInstance;
    }
    
    public Bot getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Bot_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Bot_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string ip = 1;
    public static final int IP_FIELD_NUMBER = 1;
    private java.lang.Object ip_;
    public boolean hasIp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ip_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPort() {
      return port_;
    }
    
    // required string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      ip_ = "";
      port_ = 0;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Bot_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Bot_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.getDefaultInstance()) return this;
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasIp()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ip_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              port_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string ip = 1;
      private java.lang.Object ip_ = "";
      public boolean hasIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      void setIp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
      }
      
      // required int32 port = 2;
      private int port_ ;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPort() {
        return port_;
      }
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 3;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.Bot)
    }
    
    static {
      defaultInstance = new Bot(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.Bot)
  }
  
  public interface BotCollectionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .edu.dhbw.mannheim.tigers.sumatra.proto.Bot bot = 1;
    java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot> 
        getBotList();
    edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot getBot(int index);
    int getBotCount();
    java.util.List<? extends edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotOrBuilder> 
        getBotOrBuilderList();
    edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotOrBuilder getBotOrBuilder(
        int index);
  }
  public static final class BotCollection extends
      com.google.protobuf.GeneratedMessage
      implements BotCollectionOrBuilder {
    // Use BotCollection.newBuilder() to construct.
    private BotCollection(Builder builder) {
      super(builder);
    }
    private BotCollection(boolean noInit) {}
    
    private static final BotCollection defaultInstance;
    public static BotCollection getDefaultInstance() {
      return defaultInstance;
    }
    
    public BotCollection getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotCollection_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotCollection_fieldAccessorTable;
    }
    
    // repeated .edu.dhbw.mannheim.tigers.sumatra.proto.Bot bot = 1;
    public static final int BOT_FIELD_NUMBER = 1;
    private java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot> bot_;
    public java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot> getBotList() {
      return bot_;
    }
    public java.util.List<? extends edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotOrBuilder> 
        getBotOrBuilderList() {
      return bot_;
    }
    public int getBotCount() {
      return bot_.size();
    }
    public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot getBot(int index) {
      return bot_.get(index);
    }
    public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotOrBuilder getBotOrBuilder(
        int index) {
      return bot_.get(index);
    }
    
    private void initFields() {
      bot_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getBotCount(); i++) {
        if (!getBot(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < bot_.size(); i++) {
        output.writeMessage(1, bot_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < bot_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bot_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotCollection_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotCollection_fieldAccessorTable;
      }
      
      // Construct using edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBotFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (botBuilder_ == null) {
          bot_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          botBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection.getDescriptor();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection getDefaultInstanceForType() {
        return edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection.getDefaultInstance();
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection build() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection buildPartial() {
        edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection result = new edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection(this);
        int from_bitField0_ = bitField0_;
        if (botBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            bot_ = java.util.Collections.unmodifiableList(bot_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.bot_ = bot_;
        } else {
          result.bot_ = botBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection) {
          return mergeFrom((edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection other) {
        if (other == edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection.getDefaultInstance()) return this;
        if (botBuilder_ == null) {
          if (!other.bot_.isEmpty()) {
            if (bot_.isEmpty()) {
              bot_ = other.bot_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBotIsMutable();
              bot_.addAll(other.bot_);
            }
            onChanged();
          }
        } else {
          if (!other.bot_.isEmpty()) {
            if (botBuilder_.isEmpty()) {
              botBuilder_.dispose();
              botBuilder_ = null;
              bot_ = other.bot_;
              bitField0_ = (bitField0_ & ~0x00000001);
              botBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBotFieldBuilder() : null;
            } else {
              botBuilder_.addAllMessages(other.bot_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getBotCount(); i++) {
          if (!getBot(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder subBuilder = edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBot(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .edu.dhbw.mannheim.tigers.sumatra.proto.Bot bot = 1;
      private java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot> bot_ =
        java.util.Collections.emptyList();
      private void ensureBotIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          bot_ = new java.util.ArrayList<edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot>(bot_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotOrBuilder> botBuilder_;
      
      public java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot> getBotList() {
        if (botBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bot_);
        } else {
          return botBuilder_.getMessageList();
        }
      }
      public int getBotCount() {
        if (botBuilder_ == null) {
          return bot_.size();
        } else {
          return botBuilder_.getCount();
        }
      }
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot getBot(int index) {
        if (botBuilder_ == null) {
          return bot_.get(index);
        } else {
          return botBuilder_.getMessage(index);
        }
      }
      public Builder setBot(
          int index, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot value) {
        if (botBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBotIsMutable();
          bot_.set(index, value);
          onChanged();
        } else {
          botBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBot(
          int index, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder builderForValue) {
        if (botBuilder_ == null) {
          ensureBotIsMutable();
          bot_.set(index, builderForValue.build());
          onChanged();
        } else {
          botBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBot(edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot value) {
        if (botBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBotIsMutable();
          bot_.add(value);
          onChanged();
        } else {
          botBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBot(
          int index, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot value) {
        if (botBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBotIsMutable();
          bot_.add(index, value);
          onChanged();
        } else {
          botBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBot(
          edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder builderForValue) {
        if (botBuilder_ == null) {
          ensureBotIsMutable();
          bot_.add(builderForValue.build());
          onChanged();
        } else {
          botBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBot(
          int index, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder builderForValue) {
        if (botBuilder_ == null) {
          ensureBotIsMutable();
          bot_.add(index, builderForValue.build());
          onChanged();
        } else {
          botBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBot(
          java.lang.Iterable<? extends edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot> values) {
        if (botBuilder_ == null) {
          ensureBotIsMutable();
          super.addAll(values, bot_);
          onChanged();
        } else {
          botBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBot() {
        if (botBuilder_ == null) {
          bot_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          botBuilder_.clear();
        }
        return this;
      }
      public Builder removeBot(int index) {
        if (botBuilder_ == null) {
          ensureBotIsMutable();
          bot_.remove(index);
          onChanged();
        } else {
          botBuilder_.remove(index);
        }
        return this;
      }
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder getBotBuilder(
          int index) {
        return getBotFieldBuilder().getBuilder(index);
      }
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotOrBuilder getBotOrBuilder(
          int index) {
        if (botBuilder_ == null) {
          return bot_.get(index);  } else {
          return botBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotOrBuilder> 
           getBotOrBuilderList() {
        if (botBuilder_ != null) {
          return botBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bot_);
        }
      }
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder addBotBuilder() {
        return getBotFieldBuilder().addBuilder(
            edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.getDefaultInstance());
      }
      public edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder addBotBuilder(
          int index) {
        return getBotFieldBuilder().addBuilder(
            index, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.getDefaultInstance());
      }
      public java.util.List<edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder> 
           getBotBuilderList() {
        return getBotFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotOrBuilder> 
          getBotFieldBuilder() {
        if (botBuilder_ == null) {
          botBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder, edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotOrBuilder>(
                  bot_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          bot_ = null;
        }
        return botBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.dhbw.mannheim.tigers.sumatra.proto.BotCollection)
    }
    
    static {
      defaultInstance = new BotCollection(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.dhbw.mannheim.tigers.sumatra.proto.BotCollection)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Bot_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Bot_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotCollection_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotCollection_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tbot.proto\022&edu.dhbw.mannheim.tigers.su" +
      "matra.proto\"-\n\003Bot\022\n\n\002ip\030\001 \002(\t\022\014\n\004port\030\002" +
      " \002(\005\022\014\n\004name\030\003 \002(\t\"I\n\rBotCollection\0228\n\003b" +
      "ot\030\001 \003(\0132+.edu.dhbw.mannheim.tigers.suma" +
      "tra.proto.BotB9\n,edu.dhbw.mannheim.tiger" +
      "s.sumatra.proto.modelB\tBotProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Bot_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Bot_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_Bot_descriptor,
              new java.lang.String[] { "Ip", "Port", "Name", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.Bot.Builder.class);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotCollection_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotCollection_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_edu_dhbw_mannheim_tigers_sumatra_proto_BotCollection_descriptor,
              new java.lang.String[] { "Bot", },
              edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection.class,
              edu.dhbw.mannheim.tigers.sumatra.proto.model.BotProtos.BotCollection.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
