services:
  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana_data:/var/lib/grafana
      - ../modules/moduli-statistics-saver/grafana/dashboards:/dashboards
      - ../modules/moduli-statistics-saver/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../modules/moduli-statistics-saver/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-fCQW904U3mtzui8MAAxXXE7i1DN2gphY}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    user: "1000:1000"
    depends_on:
      - influxdb
    networks:
      - statistics

  influxdb:
    image: influxdb:1.8
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - statistics

volumes:
  grafana_data:
  influxdb_data:

networks:
  statistics:
