:imagesdir: ../images

[[section-concepts]]
== Cross-cutting Concepts
// https://docs.arc42.org/section-8/

=== Under-the-hood

==== Configuration

We use a custom configuration system called configurable to be able to quickly create and manage config parameters.
The code was once part of Sumatra and was extracted to github later for reuse.

Configs are defined in your code as class members and appear in the Config Editor where they can be changed on the fly.
Additionally, they are saved in XML files.

The lib is documented on github: https://github.com/g3force/configurable

===== Set AI-dependent configs

You can define different values for each AI color in Metis, without any further definitions/registrations/etc.

Simply define spezies with the team colors and an empty spezi as default (for real matches):

```java
@Configurable(spezis = { "", "YELLOW", "BLUE" }, defValueSpezis = { "true", "false", "true" })
private boolean useManToManMarker = true;
```

Why only in Metis?
Because here we have a single instance for each calculator per AI that is not instantiated more than once.
Plays, roles and skills on the other hand require an update on each new instantiation.
See: `Metis#afterApply()`

Keep in mind that making these configs persistent might confuse other developers, so consider setting the same default value for both AIs.

==== Recording match data

We use the object database Oracle Berkeley DB Java Edition (http://www.oracle.com/technetwork/database/berkeleydb/overview/index-093405.html) for saving all the match data.

Each recording is associated with one database.
A database is a folder containing some metadata files and numerated data files.
They are stored in `data/record/`.

All classes that should be persisted need to meet following requirements:
* Must be annotated with `@com.sleepycat.persist.model.Persistent` (except for the few entities, which need `@Entity`)
* Must have a no-args constructor which can be private
* Fields that should not be persistent can be marked with `transient`

The database supports mutations if older databases need to be converted to an altered class structure.
Some changes do not need a mutations at all.
Sometimes, it is sufficient to increment the version in the class annotation.
Mutations can be added here: `RecordManager#getMutations()`

include::08_concepts_ai.adoc[]
