/*
 * Copyright (c) 2009 - 2018, DHBW Mannheim - TIGERs Mannheim
 */
package edu.tigers.sumatra.view.referee;

import edu.tigers.sumatra.RefboxRemoteControl.SSL_RefereeRemoteControlRequest;


/**
 * Listens on events generated by the gui
 * 
 * @author Gero
 */
public interface ICreateRefereeMsgObserver
{
	/**
	 * New refbox control request.
	 * 
	 * @param request
	 */
	void onRefBoxRequest(SSL_RefereeRemoteControlRequest request);
	
	
	/**
	 * Should we receive external referee cmds?
	 * 
	 * @param receive
	 */
	void onEnableReceive(boolean receive);
}
