/*
 * *********************************************************
 * Copyright (c) 2009 - 2011, DHBW Mannheim - Tigers Mannheim
 * Project: TIGERS - Sumatra
 * Date: 07.12.2011
 * Author(s): Gero
 * 
 * *********************************************************
 */
package edu.dhbw.mannheim.tigers.sumatra.view.referee;

import edu.dhbw.mannheim.tigers.sumatra.model.data.Referee.SSL_Referee.Command;


/**
 * Listens on events generated by the gui
 * 
 * @author Gero
 */
public interface ICreateRefereeMsgObserver
{
	/**
	 * Called by the gui when the "send" btn is pressed
	 * 
	 * @param id
	 * @param cmd
	 * @param goalsBlue
	 * @param goalsYellow
	 * @param timeLeft
	 */
	void onSendOwnRefereeMsg(int id, Command cmd, int goalsBlue, int goalsYellow, short timeLeft);
}
