{
 "title": "Match Stats",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:05:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "sumatraVersion",
    "label": "Sumatra Version",
    "query": "show tag values with key = \"sumatra.version\""
   },
   {
    "name": "teamName",
    "label": "Team Name",
    "query": "show tag values with key = \"team.name\""
   },
   {
    "name": "teamColor",
    "label": "Team Color",
    "query": "show tag values with key = \"team.color\""
   },
   {
    "name": "identifier",
    "label": "Identifier",
    "query": "SHOW TAG VALUES WITH KEY = \"identifier\" WHERE \"sumatra.version\" =~ /$sumatraVersion/ AND \"team.name\" =~ /$teamName/  AND \"team.color\" =~ /$teamColor/ "
   }
  ]
 },
 "panels": [
  {
   "title": "Ball Possession - $identifier",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "repeat": "identifier",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ball.possession",
     "query": "SELECT mean(\"we\") AS \"we\", mean(\"they\") AS \"they\", mean(\"both\") AS \"both\", mean(\"no_one\") AS \"no_one\" FROM \"autogen\".\"ball.possession\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "they" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "they" ], "type": "alias" }
      ],
      [
       { "params": [ "both" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "both" ], "type": "alias" }
      ],
      [
       { "params": [ "we" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "we" ], "type": "alias" }
      ],
      [
       { "params": [ "no_one" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "no_one" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Ball Possession - $identifier",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ball.possession",
     "query": "SELECT mean(\"we\") AS \"we\", mean(\"they\") AS \"they\", mean(\"both\") AS \"both\", mean(\"no_one\") AS \"no_one\" FROM \"autogen\".\"ball.possession\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "they" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "they" ], "type": "alias" }
      ],
      [
       { "params": [ "both" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "both" ], "type": "alias" }
      ],
      [
       { "params": [ "we" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "we" ], "type": "alias" }
      ],
      [
       { "params": [ "no_one" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "no_one" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Overall ball possession - $identifier",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "repeat": "identifier",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ball.possession",
     "query": "SELECT sum(\"we\") AS \"we\", sum(\"they\") AS \"they\", sum(\"both\") AS \"both\", sum(\"no_one\") AS \"no_one\" FROM \"ball.possession\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "we" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "we" ], "type": "alias" }
      ],
      [
       { "params": [ "they" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "they" ], "type": "alias" }
      ],
      [
       { "params": [ "no_one" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "no_one" ], "type": "alias" }
      ],
      [
       { "params": [ "both" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "both" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Overall ball possession - $identifier",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ball.possession",
     "query": "SELECT sum(\"we\") AS \"we\", sum(\"they\") AS \"they\", sum(\"both\") AS \"both\", sum(\"no_one\") AS \"no_one\" FROM \"ball.possession\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "we" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "we" ], "type": "alias" }
      ],
      [
       { "params": [ "they" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "they" ], "type": "alias" }
      ],
      [
       { "params": [ "no_one" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "no_one" ], "type": "alias" }
      ],
      [
       { "params": [ "both" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "both" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncovered angle - $identifier",
   "type": "gauge",
   "description": "Note: Not correctly corrected for more then one identifier. Fixed in Grafana 6.1.0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "repeat": "identifier",
   "targets": [
    {
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "defense_coverage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncovered angle - $identifier",
   "type": "gauge",
   "description": "Note: Not correctly corrected for more then one identifier. Fixed in Grafana 6.1.0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "defense_coverage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncovered angle to goal - $identifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "repeat": "identifier",
   "yaxes": [
    { "format": "degree", "label": "Uncovered angle" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statistics",
     "query": "SELECT moving_average(mean(\"defense_coverage\"), 10) AS \"coverage\" FROM \"statistics\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "defense_coverage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "coverage" ], "type": "alias" }
      ],
      [
       { "params": [ "defense_coverage_overall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "coverage_overall" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_coverage_attacker_near_ball"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "coverage_attacker_near_ball" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncovered angle to goal - $identifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "degree", "label": "Uncovered angle" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statistics",
     "query": "SELECT moving_average(mean(\"defense_coverage\"), 10) AS \"coverage\" FROM \"statistics\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "defense_coverage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "coverage" ], "type": "alias" }
      ],
      [
       { "params": [ "defense_coverage_overall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "coverage_overall" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_coverage_attacker_near_ball"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "coverage_attacker_near_ball" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Role number distribution - $identifier",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "repeat": "identifier",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ai.role.number",
     "query": "SELECT mean(\"offensive\") AS \"offense\", mean(\"support\") AS \"support\", mean(\"defensive\") AS \"defender\", mean(\"all\") AS \"all\" FROM \"ai.role.number\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "offensive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "offense" ], "type": "alias" }
      ],
      [
       { "params": [ "support" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "support" ], "type": "alias" }
      ],
      [
       { "params": [ "defensive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "defender" ], "type": "alias" }
      ],
      [
       { "params": [ "all" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "all" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Role number distribution - $identifier",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ai.role.number",
     "query": "SELECT mean(\"offensive\") AS \"offense\", mean(\"support\") AS \"support\", mean(\"defensive\") AS \"defender\", mean(\"all\") AS \"all\" FROM \"ai.role.number\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "offensive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "offense" ], "type": "alias" }
      ],
      [
       { "params": [ "support" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "support" ], "type": "alias" }
      ],
      [
       { "params": [ "defensive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "defender" ], "type": "alias" }
      ],
      [
       { "params": [ "all" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "all" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Ball Position - $identifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "repeat": "identifier",
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ball.pos",
     "query": "SELECT mean(\"x\") AS \"x\", mean(\"y\") AS \"y\", mean(\"z\") AS \"z\" FROM \"ball.pos\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "x" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "x" ], "type": "alias" }
      ],
      [
       { "params": [ "y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "y" ], "type": "alias" }
      ],
      [
       { "params": [ "z" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "z" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Ball Position - $identifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ball.pos",
     "query": "SELECT mean(\"x\") AS \"x\", mean(\"y\") AS \"y\", mean(\"z\") AS \"z\" FROM \"ball.pos\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "x" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "x" ], "type": "alias" }
      ],
      [
       { "params": [ "y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "y" ], "type": "alias" }
      ],
      [
       { "params": [ "z" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "z" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Ball Velocity - $identifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "repeat": "identifier",
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ball.pos",
     "query": "SELECT mean(\"x\") AS \"x\", mean(\"y\") AS \"y\", mean(\"z\") AS \"z\", mean(\"abs\") AS \"abs\" FROM \"ball.vel\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "x" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "x" ], "type": "alias" }
      ],
      [
       { "params": [ "y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "y" ], "type": "alias" }
      ],
      [
       { "params": [ "z" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "z" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Ball Velocity - $identifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ball.pos",
     "query": "SELECT mean(\"x\") AS \"x\", mean(\"y\") AS \"y\", mean(\"z\") AS \"z\", mean(\"abs\") AS \"abs\" FROM \"ball.vel\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "x" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "x" ], "type": "alias" }
      ],
      [
       { "params": [ "y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "y" ], "type": "alias" }
      ],
      [
       { "params": [ "z" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "z" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Closest Bot to Ball Distance - $identifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "repeat": "identifier",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ball.dist",
     "query": "SELECT mean(\"bot.they\") AS \"bot.they\", mean(\"bot.we\") AS \"bot.we\" FROM \"ball.dist\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bot.they" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "they" ], "type": "alias" }
      ],
      [
       { "params": [ "bot.we" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "we" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Closest Bot to Ball Distance - $identifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ball.dist",
     "query": "SELECT mean(\"bot.they\") AS \"bot.they\", mean(\"bot.we\") AS \"bot.we\" FROM \"ball.dist\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bot.they" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "they" ], "type": "alias" }
      ],
      [
       { "params": [ "bot.we" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "we" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Misc - $identifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "repeat": "identifier",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statistics",
     "query": "SELECT mean(\"direct_shots\") AS \"direct_shots\", mean(\"count_passes\") AS \"count_passes\", mean(\"goals_scored\") AS \"goals_scored\", mean(\"active_pass_target\") AS \"active_pass_target\" FROM \"statistics\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "direct_shots" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "direct_shots" ], "type": "alias" }
      ],
      [
       { "params": [ "count_passes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "count_passes" ], "type": "alias" }
      ],
      [
       { "params": [ "goals_scored" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "goals_scored" ], "type": "alias" }
      ],
      [
       { "params": [ "active_pass_target" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active_pass_target" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Misc - $identifier",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statistics",
     "query": "SELECT mean(\"direct_shots\") AS \"direct_shots\", mean(\"count_passes\") AS \"count_passes\", mean(\"goals_scored\") AS \"goals_scored\", mean(\"active_pass_target\") AS \"active_pass_target\" FROM \"statistics\" WHERE (\"startTime\" =~ /^$startTime$/ AND \"team.color\" =~ /^$teamColor$/ AND \"team.name\" =~ /^$teamName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "direct_shots" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "direct_shots" ], "type": "alias" }
      ],
      [
       { "params": [ "count_passes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "count_passes" ], "type": "alias" }
      ],
      [
       { "params": [ "goals_scored" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "goals_scored" ], "type": "alias" }
      ],
      [
       { "params": [ "active_pass_target" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active_pass_target" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  }
 ]
}