{
 "title": "Match Stats Overview",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:05:00.000Z" },
 "panels": [
  {
   "title": "Goals and Cards",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "referee",
     "query": "SELECT last(\"goals.we\") as \"Our Goals\", last(\"goals.they\") as \"Their Goals\", last(\"cards.yellow.we\") as \"Our Yellow Cards\", last(\"cards.yellow.their\") as \"Their Yellow Cards\", last(\"cards.red.we\") as \"Our Red Cards\", last(\"cards.red.their\") as \"Their Red Cards\" FROM \"referee\" WHERE $timeFilter GROUP BY \"identifier\"",
     "select": [
      [
       { "params": [ "goals.we" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "goals.they" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "cards.yellow.we" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "cards.yellow.their" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "cards.red.we" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "cards.red.their" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ball possession",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ball.possession",
     "query": "SELECT sum(\"we\") / (sum(\"we\") + sum(\"they\") + sum(\"both\") + sum(\"no_one\")) as \"we\", sum(\"they\") / (sum(\"we\") + sum(\"they\") + sum(\"both\") + sum(\"no_one\")) as \"they\" FROM \"ball.possession\" WHERE $timeFilter GROUP BY identifier",
     "select": [
      [
       { "params": [ "we" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uncovered angle to own goal",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "defense_coverage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "defense_coverage" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "P95" ], "type": "alias" }
      ],
      [
       { "params": [ "defense_coverage" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "P90" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}