{
 "title": "Defense Stats",
 "tags": [ "Defense" ],
 "time": { "from": "1969-12-31T11:00:00.000Z", "to": "1970-01-02T11:00:00.000Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_MATCHSTATS", "label": "Datasource", "query": "influxdb" },
   {
    "name": "sumatraVersion",
    "label": "Sumatra Version",
    "query": "show tag values with key = \"sumatra.version\""
   },
   {
    "name": "teamName",
    "label": "Team Name",
    "query": "show tag values with key = \"team.name\""
   },
   {
    "name": "teamColor",
    "label": "Team Color",
    "query": "show tag values with key = \"team.color\""
   },
   {
    "name": "identifier",
    "label": "Identifier",
    "query": "SHOW TAG VALUES WITH KEY = \"identifier\" WHERE \"sumatra.version\" =~ /$sumatraVersion/ AND \"team.name\" =~ /$teamName/  AND \"team.color\" =~ /$teamColor/ "
   }
  ]
 },
 "panels": [
  { "title": "Overview Per Team Name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Common Stats",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" },
      { "params": [ "team.name" ], "type": "tag" }
     ],
     "measurement": "referee",
     "select": [
      [
       { "params": [ "goals.we" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Goals We" ], "type": "alias" }
      ],
      [
       { "params": [ "goals.they" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "GoalsThey" ], "type": "alias" }
      ],
      [
       { "params": [ "cards.yellow.we" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Yellow Cards" ], "type": "alias" }
      ],
      [
       { "params": [ "cards.red.we" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Red Cards" ], "type": "alias" }
      ],
      [
       { "params": [ "foul.counter.we" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Fouls" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncovered Goal Angle",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "team.name" ], "type": "tag" }
     ],
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "defense_coverage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_coverage_attacker_near_ball"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Near Ball" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_coverage_at_ball_received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "At Receive" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Defense Bot Threat Rating per Team Name",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "team.name" ], "type": "tag" }
     ],
     "measurement": "statistics",
     "query": "SELECT mean(\"defense_bot_threat_rating_actual\") FROM \"statistics\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "defense_bot_threat_rating_actual"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Actual" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_bot_threat_rating_wanted"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wanted" ], "type": "alias" }
      ],
      [
       { "params": [ "defense_bot_threat_rating_raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "0 Defender" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Defense Stats when Attacker receives Ball",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "team.name" ], "type": "tag" }
     ],
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "defense_dist_at_ball_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "BallDefender distance" ], "type": "alias" }
      ],
      [
       { "params": [ "defense_vel_at_ball_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "BallDefender vel diff" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_coverage_at_ball_received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Goal coverage" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_ball_pos_x_at_ball_received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ball Pos X" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  { "title": "Fouls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Fouls Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "NEUTRAL" ], "type": "field" }
      ],
      [
       { "params": [ "YELLOW" ], "type": "field" }
      ],
      [
       { "params": [ "BLUE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "BOT_CRASH_UNIQUE",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "YELLOW" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 20 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "YELLOW" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "BOT_DRIBBLED_BALL_TOO_FAR",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 20 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "YELLOW" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "KEEPER_HELD_BALL",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 20 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "YELLOW" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "BOT_KICKED_BALL_TOO_FAST",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 20 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "YELLOW" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "BOT_CRASH_DRAWN",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "NEUTRAL" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "BOT_CRASH_UNIQUE",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "BLUE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 22 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "BLUE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "BOT_DRIBBLED_BALL_TOO_FAR",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 22 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "BLUE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "KEEPER_HELD_BALL",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 22 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "BLUE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  {
   "title": "BOT_KICKED_BALL_TOO_FAST",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 22 },
   "targets": [
    {
     "measurement": "foulEvents",
     "select": [
      [
       { "params": [ "BLUE" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "team.color", "operator": "=", "value": "yellow" }
     ]
    }
   ]
  },
  { "title": "Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Common Stats",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" },
      { "params": [ "team.name" ], "type": "tag" }
     ],
     "measurement": "referee",
     "select": [
      [
       { "params": [ "goals.we" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "GoalsBlue" ], "type": "alias" }
      ],
      [
       { "params": [ "cards.yellow.we" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Yellow Cards Blue" ], "type": "alias" }
      ],
      [
       { "params": [ "cards.red.we" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Red Cards Blue" ], "type": "alias" }
      ],
      [
       { "params": [ "foul.counter.we" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Fouls Blue" ], "type": "alias" }
      ],
      [
       { "params": [ "goals.they" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Goals Yellow" ], "type": "alias" }
      ],
      [
       { "params": [ "cards.yellow.their" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Yellow Cards Yellow" ], "type": "alias" }
      ],
      [
       { "params": [ "cards.red.their" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Red Cards Yellow" ], "type": "alias" }
      ],
      [
       { "params": [ "foul.counter.their" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Fouls Yellow" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" },
      { "condition": "AND", "key": "team.color", "operator": "=", "value": "blue" }
     ]
    }
   ]
  },
  {
   "title": "Defense Bot Threat Rating per Identifier",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "statistics",
     "query": "SELECT mean(\"defense_bot_threat_rating_actual\") FROM \"statistics\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "defense_bot_threat_rating_actual"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Actual" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_bot_threat_rating_wanted"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Wanted" ], "type": "alias" }
      ],
      [
       { "params": [ "defense_bot_threat_rating_raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "0 Defender" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncovered Goal Angle",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "defense_coverage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_coverage_attacker_near_ball"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Near Ball" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_coverage_at_ball_received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "At Receive" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  },
  {
   "title": "Defense Stats when Attacker receives Ball per Identifier",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" }
     ],
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "defense_dist_at_ball_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Distance" ], "type": "alias" }
      ],
      [
       { "params": [ "defense_vel_at_ball_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Velocity diff" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_coverage_at_ball_received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Coverage" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "defense_ball_pos_x_at_ball_received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ball Pos X" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "identifier", "operator": "=~", "value": "/^$identifier$/" }
     ]
    }
   ]
  }
 ]
}