{
 "title": "Match Stats Overview",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-02T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Goals and Cards",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT last(\"goals.we\") as \"Our Goals\", last(\"goals.they\") as \"Their Goals\", last(\"cards.yellow.we\") as \"Our Yellow Cards\", last(\"cards.yellow.their\") as \"Their Yellow Cards\", last(\"cards.red.we\") as \"Our Red Cards\", last(\"cards.red.their\") as \"Their Red Cards\" FROM \"referee\" WHERE $timeFilter GROUP BY \"identifier\""
    }
   ]
  },
  {
   "title": "Ball possession",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "SELECT sum(\"we\") / (sum(\"we\") + sum(\"they\") + sum(\"both\") + sum(\"no_one\")) as \"we\", sum(\"they\") / (sum(\"we\") + sum(\"they\") + sum(\"both\") + sum(\"no_one\")) as \"they\" FROM \"ball.possession\" WHERE $timeFilter GROUP BY identifier"
    }
   ]
  },
  {
   "title": "Direct Shots (With Reasons for Failure)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" },
      { "params": [ "team.name" ], "type": "tag" }
     ],
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "direct_shots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "direct_shots_blocked_defense" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "defense" ], "type": "alias" }
      ],
      [
       { "params": [ "direct_shots_blocked_keeper" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "keeper" ], "type": "alias" }
      ],
      [
       { "params": [ "direct_shots_blocked_both" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "both" ], "type": "alias" }
      ],
      [
       { "params": [ "direct_shots_skirmish" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "skirmish" ], "type": "alias" }
      ],
      [
       { "params": [ "direct_shots_other" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "other" ], "type": "alias" }
      ],
      [
       { "params": [ "direct_shots_success" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "success" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Calculation Time",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "identifier" ], "type": "tag" },
      { "params": [ "team.name" ], "type": "tag" }
     ],
     "measurement": "ai",
     "select": [
      [
       { "params": [ "endTime" ], "type": "field" },
       { "params": [ "end" ], "type": "alias" }
      ],
      [
       { "params": [ "startTime" ], "type": "field" },
       { "params": [ "start" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uncovered angle to own goal",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "SELECT mean(\"defense_coverage\"), percentile(\"defense_coverage\", 95) AS \"P95\", percentile(\"defense_coverage\", 90) AS \"P90\" FROM \"statistics\" WHERE $timeFilter GROUP BY \"identifier\""
    }
   ]
  }
 ]
}