{
 "title": "Match Stats",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:05:00.000Z" },
 "templating": {
  "list": [
   { "name": "DS_MATCHSTATS", "label": "Datasource", "query": "influxdb" },
   {
    "name": "sumatraVersion",
    "label": "Sumatra Version",
    "query": "show tag values with key = \"sumatra.version\""
   },
   {
    "name": "teamName",
    "label": "Team Name",
    "query": "show tag values with key = \"team.name\""
   },
   {
    "name": "teamColor",
    "label": "Team Color",
    "query": "show tag values with key = \"team.color\""
   },
   {
    "name": "identifier",
    "label": "Identifier",
    "query": "SHOW TAG VALUES WITH KEY = \"identifier\" WHERE \"sumatra.version\" =~ /$sumatraVersion/ AND \"team.name\" =~ /$teamName/  AND \"team.color\" =~ /$teamColor/ "
   }
  ]
 },
 "panels": [
  {
   "title": "Ball Possession - $identifier",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "repeat": "identifier",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT mean(\"they\") AS \"they\", mean(\"both\") AS \"both\", mean(\"we\") AS \"we\", mean(\"no_one\") AS \"no_one\" FROM \"autogen\".\"ball.possession\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  {
   "title": "Overall ball possession - $identifier",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "repeat": "identifier",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"we\") AS \"we\", sum(\"they\") AS \"they\", sum(\"no_one\") AS \"no_one\", sum(\"both\") AS \"both\" FROM \"ball.possession\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Uncovered angle - $identifier",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "repeat": "identifier",
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT \"defense_coverage\" FROM \"autogen\".\"statistics\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Uncovered angle to goal - $identifier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "repeat": "identifier",
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "SELECT moving_average(mean(\"defense_coverage\"), 10) AS \"coverage\", moving_average(mean(\"defense_coverage_overall\"), 10) AS \"coverage_overall\", moving_average(mean(\"defense_coverage_attacker_near_ball\"), 10) AS \"coverage_attacker_near_ball\" FROM \"statistics\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Role number distribution - $identifier",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "repeat": "identifier",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT mean(\"offensive\") AS \"offense\", mean(\"support\") AS \"support\", mean(\"defensive\") AS \"defender\", mean(\"all\") AS \"all\" FROM \"ai.role.number\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Ball Position - $identifier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "repeat": "identifier",
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "SELECT mean(\"x\") AS \"x\", mean(\"y\") AS \"y\", mean(\"z\") AS \"z\" FROM \"ball.pos\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Ball Velocity - $identifier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "repeat": "identifier",
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "SELECT mean(\"x\") AS \"x\", mean(\"y\") AS \"y\", mean(\"z\") AS \"z\" FROM \"ball.vel\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Closest Bot to Ball Distance - $identifier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "repeat": "identifier",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT mean(\"bot.they\") AS \"they\", mean(\"bot.we\") AS \"we\" FROM \"ball.dist\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Misc - $identifier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "repeat": "identifier",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT mean(\"direct_shots\") AS \"direct_shots\", mean(\"count_passes\") AS \"count_passes\", mean(\"goals_scored\") AS \"goals_scored\", mean(\"active_pass_target\") AS \"active_pass_target\" FROM \"statistics\" WHERE (\"identifier\" =~ /^$identifier$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}