/*
 * Copyright (c) 2009 - 2017, DHBW Mannheim - TIGERs Mannheim
 */

package edu.tigers.sumatra.ai.data;

import java.util.Map;

import edu.tigers.sumatra.ids.BotID;


/**
 * Data generated by {@link edu.tigers.sumatra.ai.ares.Ares}
 *
 * @author Nicolai Ommer <nicolai.ommer@gmail.com>
 */
public interface IAresData
{
	/**
	 * @return
	 */
	Map<BotID, BotAiInformation> getBotAiInformation();
}
